export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export type SHOW_NOTIFICATION = typeof SHOW_NOTIFICATION;

export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export type HIDE_NOTIFICATION = typeof HIDE_NOTIFICATION;
